#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (C) 2007 daniel g. siegel <dgsiegel@gmail.com>
#
# Licensed under the GNU General Public License Version 2
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

install_files('PACKAGE_DATADIR', '', 'cheese.glade')
install_files('PACKAGE_DATADIR', '', '*.glade')

# process .in files with intl_tool
obj=bld.create_obj('gnome_intltool')
obj.source  = 'gnome-packagekit.schemas.in'
obj.destvar = 'PREFIX'
obj.subdir  = 'etc/gconf/schemas'
obj.podir   = '../po'
obj.flags   = '-s'

for i in ["pk-application.desktop.in", "pk-transaction-viewer.desktop.in", 
	  "pk-install-file.desktop.in", "pk-update-icon.desktop.in", 
	  "pk-prefs.desktop.in", "pk-update-viewer.desktop.in", "pk-repo.desktop.in"]:
	obj=bld.create_obj('gnome_intltool')
	obj.source  = i
	obj.destvar = 'PREFIX'
	obj.subdir  = 'share/applications'
	obj.podir   = '../po'
	obj.flags   = '-d'

# data/icons
for i in ["16x16", "22x22", "24x24", "48x48"]:
	install_files('DATADIR', 'icons/hicolor/%s/status/*.png' % i, 'icons/%s/' % i)
	install_files('DATADIR', 'icons/hicolor/%s/categories/*.png' % i, 'icons/%s/' % i)
install_files('DATADIR', 'icons/hicolor/%s/status/*.svg' % i, 'icons/%s/' % i)
install_files('DATADIR', 'icons/hicolor/%s/categories/*.svg' % i, 'icons/%s/' % i)


